language: python
sudo: false
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
  fast_finish: true
addons:
  apt:
    packages:
      - libxmlsec1-dev
      - swig
install:
  - pip install tox -U pip
script:
  - tox -e $TOXENV
